services:
  api:
    image: python:3.9
    container_name: fastapi-application
    command: >
      /bin/sh -c "
      echo 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get(\"/\")\ndef read_root():\n    return {\"Hello\": \"World\"}' > main.py &&
      pip install uvicorn[standard]==0.20.0 gunicorn==20.1.0 fastapi[all]==0.88.0 &&
      uvicorn main:app --host 0.0.0.0 --port 4300"
    volumes:
      - ./app:/app
    ports:
      - '7587:7587'
    restart: "always"

    
